# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category1', models.CharField(choices=[('music', 'Music'), ('business', 'Business & Professional'), ('food', 'Food & Drink'), ('community', 'Community & Culture'), ('performing', 'Performing & Visual Arts'), ('film', 'Film, Media & Entertainment'), ('sports', 'Sports & Fitness'), ('travel', 'Travel & Outdoor'), ('charity', 'Charity & Causes'), ('religion', 'Religion & Spirituality'), ('family', 'Family & Education'), ('seasonal', 'Seasonal & Holiday'), ('government', 'Government & Politics'), ('fashion', 'Fashion & Beauty'), ('home', 'Home & Lifestyle'), ('auto', 'Auto, Boat & Air'), ('hobbies', 'Hobbies & Special Interest'), ('other', 'Other')], max_length=20)),
                ('category2', models.CharField(choices=[('music', 'Music'), ('business', 'Business & Professional'), ('food', 'Food & Drink'), ('community', 'Community & Culture'), ('performing', 'Performing & Visual Arts'), ('film', 'Film, Media & Entertainment'), ('sports', 'Sports & Fitness'), ('travel', 'Travel & Outdoor'), ('charity', 'Charity & Causes'), ('religion', 'Religion & Spirituality'), ('family', 'Family & Education'), ('seasonal', 'Seasonal & Holiday'), ('government', 'Government & Politics'), ('fashion', 'Fashion & Beauty'), ('home', 'Home & Lifestyle'), ('auto', 'Auto, Boat & Air'), ('hobbies', 'Hobbies & Special Interest'), ('other', 'Other')], max_length=20)),
                ('category3', models.CharField(choices=[('music', 'Music'), ('business', 'Business & Professional'), ('food', 'Food & Drink'), ('community', 'Community & Culture'), ('performing', 'Performing & Visual Arts'), ('film', 'Film, Media & Entertainment'), ('sports', 'Sports & Fitness'), ('travel', 'Travel & Outdoor'), ('charity', 'Charity & Causes'), ('religion', 'Religion & Spirituality'), ('family', 'Family & Education'), ('seasonal', 'Seasonal & Holiday'), ('government', 'Government & Politics'), ('fashion', 'Fashion & Beauty'), ('home', 'Home & Lifestyle'), ('auto', 'Auto, Boat & Air'), ('hobbies', 'Hobbies & Special Interest'), ('other', 'Other')], max_length=20)),
            ],
        ),
    ]
