# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 03:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topthree', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='category1',
            new_name='category_1',
        ),
        migrations.RenameField(
            model_name='categories',
            old_name='category2',
            new_name='category_2',
        ),
        migrations.RenameField(
            model_name='categories',
            old_name='category3',
            new_name='category_3',
        ),
    ]
